image:
  registry: "intel/"
  uiTag: "core_1.2.2"
  pullPolicy: IfNotPresent

global:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
  app_backend_url: "/v1/chatqna"

uiService:
  type: ClusterIP
  port: 8102
  targetPort: 8102
